### ISSUE TITLE
ImportError: No module named loaner

### ISSUE THREAD

**Issue by JoshSanchezG** [google/loaner#10]
I have edited all files, I have created the project and I executed this command:
$gcloud app deploy --version=gng20180924
And I think the application should be running normally:
$bash loaner/deployments/deploy.sh web local
$cd ../bazel-bin/loaner/web_app/runfiles.runfiles/gng/
$dev_appserver.py app.yaml
But I'm getting this error:

Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 86, in LoadObject
    is_parent_package = True
ImportError: No module named loaner

Could anybody help me please? Thanks in advance.

**Comment by JoshSanchezG** [comment]
Hello All!

I have created a new user in my laptop (Ubuntu), name: gng, downloaded the loaner folder with git and now in this user account the error has gone.
Now I can execute:
bash loaner/deployments/deploy.sh web local
cd ../bazel-bin/loaner/web_app/runfiles.runfiles/gng/
dev_appserver.py app.yaml

But nothing happen...

INFO     2018-09-27 16:26:06,082 devappserver2.py:281] Skipping SDK update check.
WARNING  2018-09-27 16:26:16,431 simple_search_stub.py:1196] Could not read search indexes from /tmp/appengine.None.gng/search_indexes
INFO     2018-09-27 16:26:16,433 api_server.py:275] Starting API server at: http://localhost:40873
INFO     2018-09-27 16:26:21,592 dispatcher.py:270] Starting module "default" running at: http://localhost:8080
INFO     2018-09-27 16:26:21,594 admin_server.py:152] Starting admin server at: http://localhost:8000
INFO     2018-09-27 16:26:23,614 instance.py:294] Instance PID: 7766

Could you help me please?

**Comment by helfrichmichael** [comment]
Can you clarify what you mean by nothing happens? Can you reach the service at localhost:8080 in your browser or 127.0.0.1:8080? If not, are there any errors in the Developer Console of your browser?

**Comment by JoshSanchezG** [comment]
Hi Michael!

Let me explain my case: when I use this command: "dev_appserver.py app.yaml" I try to open this URL: http://localhost:8080/ but I get a message: "Forbidden." and with this URL: http://127.0.0.1:8080/ I can see a login window with this email address: test@example.com, I click on "login"but I have the same message: "Forbidden.". Finally in my GCP I can see the version (gng-[date]) with the service: "default" with the status: "Serving" but the "Traffic Allocation" = 0%.

Have you seen this "error" before?

Thanks in advance.
