### ISSUE TITLE
Intermittent 401 (invalid oauth token) from Chrome API endpoint

### ISSUE THREAD

**Issue by iamgeef** [google/loaner#19]
We're seeing intermittent 401 responses from the Chrome API endpoint, when the chrome devices send a heartbeat.

```Unable to get authorized scopes. (/base/data/home/apps/f~ncau-tech-grab-n-go-prod/chrome:mcshaneg-20181104.413743242539803060/external/endpoints_archive/endpoints/users_id_token.py:371)
Traceback (most recent call last):
  File "/base/data/home/apps/f~ncau-tech-grab-n-go-prod/chrome:mcshaneg-20181104.413743242539803060/external/endpoints_archive/endpoints/users_id_token.py", line 369, in _set_bearer_user_vars
    authorized_scopes = oauth.get_authorized_scopes(sorted(all_scopes))
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/1/google/appengine/api/oauth/oauth_api.py", line 171, in get_authorized_scopes
    _maybe_call_get_oauth_user(scope)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/1/google/appengine/api/oauth/oauth_api.py", line 220, in _maybe_call_get_oauth_user
    _maybe_raise_exception()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/1/google/appengine/api/oauth/oauth_api.py", line 239, in _maybe_raise_exception
    raise InvalidOAuthTokenError(error_detail)
InvalidOAuthTokenError
```
Doesn't seem to be any specific trigger, and sometimes an initial heartbeat will be succesfull causing the device to be assigned to a user, but around 20 seconds later it'll 401 so the rest of the onboarding flow fails to appear.

I've tried using a different network, un-enrolling and re-enrolling chromebooks , using different chromebooks, using different users (both superadmin and non-superadmin), wiping the chromebooks, redeploying the web app, redeploying the chrome app, creating a new OAuth Client ID and redploying the system - nothing seems to stabilise it. 

Any help with the right direction to start troubleshooting this would be ace.

**Comment by Sasho11** [comment]
we recently pushed an update to the master branch, can you please pull those changes down and deploy another version of the application? Please let me know how that goes.
