### ISSUE TITLE
A different "can't build web app"

### ISSUE THREAD

**Issue by templesnr** [google/loaner#52]
After raising the issue in the Google + forum, it's taken me a while but I've built a new development Linux box from scratch.  I downloaded the latest Master branch but unfortunately I'm getting an error towards the end of the build web app.

I've tried to follow the errors through in the code, but I can't see what might be the cause.

Unfortunately the inability to build the application is causing a problem as I can't bootstrap and deploy a fresh instance.  I would be grateful for any help.

### Expected Behaviour
run `bash deployments/deploy.sh web prod`
to build web app
### Actual Behaviour
errors at the end of build
### Steps to Reproduce
run build again

  [27] ./web_app/frontend/src/services/device.ts 9.26 kB {0} [built]
  [33] ./web_app/frontend/src/services/shelf.ts 5.84 kB {0} [built]
  [43] ./web_app/frontend/src/services/snackbar.ts 1.57 kB {0} [built]
  [52] ./web_app/frontend/src/services/user.ts 4.27 kB {0} [built]
  [59] ./web_app/frontend/src/services/dialog/dialog.ts 1.41 kB {0} [built]
  [60] ./web_app/frontend/src/services/config.ts 5.88 kB {0} [built]
  [61] ./web_app/frontend/src/services/search.ts 3.52 kB {0} [built]
 [434] ./web_app/frontend/src/main.aot.ts 1.01 kB {0} [built]
 [598] ./web_app/frontend/src/app.module.ngfactory.js 31.8 kB {0} [built]
 [695] ./web_app/frontend/src/app.ngfactory.js 16.9 kB {0} [built]
 [699] ./web_app/frontend/src/services/oauth_interceptor.ts 5.93 kB {0} [built]
 [701] ./web_app/frontend/src/services/tag.ts 3.15 kB {0} [built]
 [707] ./shared/directives/min_validator/index.ts 1 kB {0} [built]
 [708] ./shared/directives/remove_whitespaces/index.ts 1.03 kB {0} [built]
 [712] ./shared/directives/focus/index.ts 960 bytes {0} [built]
    + 721 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./web_app/frontend/src/index.html 781 bytes {0} [built]
ERROR: /home/hackney/Dev/loaner-master/loaner/web_app/BUILD:113:1: in py_appengine_binary_base rule //loaner/web_app:runfiles: 
Traceback (most recent call last):
        File "/home/hackney/Dev/loaner-master/loaner/web_app/BUILD", line 113
                py_appengine_binary_base(name = 'runfiles')
        File "/home/hackney/.cache/bazel/_bazel_hackney/b5b8b7c184f422d566e2bb6917c490a0/external/io_bazel_rules_appengine/appengine/py_appengine.bzl", line 165, in _py_appengine_binary_base_impl
                struct(runfiles = runfiles, py = ctx.attr...)
        File "/home/hackney/.cache/bazel/_bazel_hackney/b5b8b7c184f422d566e2bb6917c490a0/external/io_bazel_rules_appengine/appengine/py_appengine.bzl", line 165, in struct
                ctx.attr.binary.py
<target //loaner/web_app:_py_appengine_runfiles> (rule 'py_binary') doesn't have provider 'py'
ERROR: Analysis of target '//loaner/web_app:runfiles' failed; build aborted: Analysis of target '//loaner/web_app:runfiles' failed; build aborted
INFO: Elapsed time: 0.300s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
hackney@hackney-gng-dev:~/Dev/loaner-master/loaner$ ^C

**Comment by gng-demo** [comment]
May I ask what kind of machine you are building on and you are on the most up to date version correct?

**Comment by templesnr** [comment]
Hi, I'm on the Master version. Building on Kde Neon.  I re-built it three or four times, trying to get the right version of npm, node and Angular .. Do you recommend anything ?

**Comment by templesnr** [comment]
well, yet another clean install of Linux later and I've managed to clean everything up.  I'll post something in G+ which might help others.  I got some inspiration from the travis stuff and some from my previous installation notes ... at least I'm able to build the web app again, which is  a relief!
