### ISSUE TITLE
server error when Auditing shelf

### ISSUE THREAD

**Issue by templesnr** [google/loaner#74]
### Expected Behaviour
Add device serial number to shelf
click Audit button
get audit success message "Shelf Test Shelf audited with devices K7NXCV03xxxxxxx"
### Actual Behaviour
ERROR: internal server error
### Steps to Reproduce
now a number of devices are receiving this error message

**Comment by helfrichmichael** [comment]
Do you have any errors in the logs on GCP (Google Cloud Platform) for this project when you execute these actions (might take 15 or so seconds for the logs to update)?

**Comment by templesnr** [comment]
I'm getting a whole stack of "over quota errors" too.  They're all the same, here's one:
`https://console.cloud.google.com/logs/viewer?resource=gae_app%2Fmodule_id%2Fdefault%2Fversion_id%2Fhackneylive-20190409&logName=projects%2Fhackney-loaner-dev%2Flogs%2Fappengine.googleapis.com%252Frequest_log&expandAll=false&timestamp=2019-10-04T16%3A52%3A16.749000000Z&project=hackney-loaner-dev&organizationId=127397986651&src=ac&minLogLevel=0&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22default%22%0Aresource.labels.zone%3D%22europe-west2-1%22%0Aresource.labels.project_id%3D%22hackney-loaner-dev%22%0Aresource.labels.version_id%3D%22hackneylive-20190409%22%0Atimestamp%3D%222019-10-04T16%3A54%3A46.754440000Z%22%0AinsertId%3D%225d977956000d19b31000dbfc%22&interval=JUMP_TO_TIME&scrollTimestamp=2019-10-04T16%3A54%3A46.754440000Z&dateRangeUnbound=forwardInTime`

`{
 httpRequest: {
  status: 500   
 }
 insertId: "5d977956000d19b31000dbfc"  
 labels: {
  clone_id: "00c61b117c8d0486b507af79947219eaa8b4b34afafec1110e0cc0f4d8b01871b98014887a"   
 }
 logName: "projects/hackney-loaner-dev/logs/appengine.googleapis.com%2Frequest_log"  
 operation: {
  first: true   
  id: "5d97795600ff0b8308741015720001677e6861636b6e65792d6c6f616e65722d64657600016861636b6e65796c6976652d3230313930343039000100"   
  last: true   
  producer: "appengine.googleapis.com/request_id"   
 }
 protoPayload: {
  @type: "type.googleapis.com/google.appengine.logging.v1.RequestLog"   
  appEngineRelease: "1.9.71"   
  appId: "g~hackney-loaner-dev"   
  cost: 6.64852e-7   
  endTime: "2019-10-04T16:54:46.858355Z"   
  finished: true   
  first: true   
  host: "default.hackney-loaner-dev.appspot.com"   
  httpVersion: "HTTP/1.1"   
  instanceId: "00c61b117c8d0486b507af79947219eaa8b4b34afafec1110e0cc0f4d8b01871b98014887a"   
  instanceIndex: -1   
  ip: "0.1.0.2"   
  latency: "0.103915s"   
  line: [
   0: {
    logMessage: "The API call mail.Send() required more quota than is available.
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/43caca2e2421b6d/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/43caca2e2421b6d/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/43caca2e2421b6d/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/43caca2e2421b6d/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/43caca2e2421b6d/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/43caca2e2421b6d/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/g~hackney-loaner-dev/hackneylive-20190409.417375074450150965/loaner/web_app/backend/handlers/task/process_emails.py", line 38, in post
    mail.send_mail(**email_dict)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/43caca2e2421b6d/python27/python27_lib/versions/1/google/appengine/api/mail.py", line 397, in send_mail
    message.send(make_sync_call=make_sync_call)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/43caca2e2421b6d/python27/python27_lib/versions/1/google/appengine/api/mail.py", line 1161, in send
    make_sync_call('mail', self._API_CALL, message, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/43caca2e2421b6d/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 97, in MakeSyncCall
    return stubmap.MakeSyncCall(service, call, request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/43caca2e2421b6d/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 331, in MakeSyncCall
    rpc.CheckSuccess()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/43caca2e2421b6d/python27/python27_lib/versions/1/google/appengine/api/apiproxy_rpc.py", line 138, in CheckSuccess
    raise self.exception
OverQuotaError: The API call mail.Send() required more quota than is available."     
    severity: "ERROR"     
    sourceLocation: {
     file: "/base/alloc/tmpfs/dynamic_runtimes/python27g/43caca2e2421b6d/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py"      
     functionName: "_internal_error"      
     line: "1552"      
    }
    time: "2019-10-04T16:54:46.856422Z"     
   }
  ]
  megaCycles: "14"   
  method: "POST"   
  referrer: "http://action-system.hackney-loaner-dev.appspot.com/_ah/queue/process-action"   
  requestId: "5d97795600ff0b8308741015720001677e6861636b6e65792d6c6f616e65722d64657600016861636b6e65796c6976652d3230313930343039000100"   
  resource: "/_ah/queue/send-email"   
  responseSize: "3260"   
  startTime: "2019-10-04T16:54:46.754440Z"   
  status: 500   
  taskName: "41349796920193448841"   
  taskQueueName: "send-email"   
  traceId: "69f06266a06ae9ee84b7d8cc150479b7"   
  traceSampled: true   
  urlMapEntry: "loaner.web_app.main.web_app"   
  userAgent: "AppEngine-Google; (+http://code.google.com/appengine)"   
  versionId: "hackneylive-20190409"   
 }
 receiveTimestamp: "2019-10-04T16:54:46.859930834Z"  
 resource: {
  labels: {
   module_id: "default"    
   project_id: "hackney-loaner-dev"    
   version_id: "hackneylive-20190409"    
   zone: "europe-west2-1"    
  }
  type: "gae_app"   
 }
 severity: "ERROR"  
 timestamp: "2019-10-04T16:54:46.754440Z"  
 trace: "projects/hackney-loaner-dev/traces/69f06266a06ae9ee84b7d8cc150479b7"  
 traceSampled: true  
}`

**Comment by templesnr** [comment]
I've tried to find evidence of the internal server error - but it's a needle in the haystack.  I think it's this one:
`Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/43caca2e2421b6d/python27/python27_lib/versions/third_party/protorpc-1.0/protorpc/wsgi/service.py", line 181, in protorpc_service_app
    response = method(instance, request)
  File "/base/data/home/apps/g~hackney-loaner-dev/endpoints:hackneylive-20190409.417375082548123112/external/endpoints_archive/endpoints/api_config.py", line 1331, in invoke_remote
    return remote_method(service_instance, request)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/43caca2e2421b6d/python27/python27_lib/versions/third_party/protorpc-1.0/protorpc/remote.py", line 414, in invoke_remote_method
    response = method(service_instance, request)
  File "/base/data/home/apps/g~hackney-loaner-dev/endpoints:hackneylive-20190409.417375082548123112/loaner/web_app/backend/api/auth.py", line 115, in wrapper
    return function_without_auth_check(*args, **kwargs)
  File "/base/data/home/apps/g~hackney-loaner-dev/endpoints:hackneylive-20190409.417375082548123112/loaner/web_app/backend/api/shelf_api.py", line 188, in audit
    device.move_to_shelf(shelf=shelf, user_email=user_email)
  File "/base/data/home/apps/g~hackney-loaner-dev/endpoints:hackneylive-20190409.417375082548123112/loaner/web_app/backend/models/device_model.py", line 862, in move_to_shelf
    self._loan_return(user_email=user_email)
  File "/base/data/home/apps/g~hackney-loaner-dev/endpoints:hackneylive-20190409.417375082548123112/loaner/web_app/backend/models/device_model.py", line 645, in _loan_return
    self.unlock(user_email)
  File "/base/data/home/apps/g~hackney-loaner-dev/endpoints:hackneylive-20190409.417375082548123112/loaner/web_app/backend/models/device_model.py", line 514, in unlock
    client.reenable_chrome_device(self.chrome_device_id)
  File "/base/data/home/apps/g~hackney-loaner-dev/endpoints:hackneylive-20190409.417375082548123112/loaner/web_app/backend/clients/directory.py", line 298, in reenable_chrome_device
    raise DirectoryRPCError(err.resp.reason)
DirectoryRPCError: Precondition Failed`

**Comment by winnie-lam** [comment]
Hi, 

Was this issue resolved? If so, how?

Thank you!

**Comment by helfrichmichael** [comment]
@templesnr can you provide an update as to whether you resolved this or not?
